---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории. 1.0
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д. 1.1
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре. 1.2
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины. 1.3
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы. 2.0
  - Сайт должен быть безопасным и защищать данные пользователя. 2.1
  - Сайт должен иметь мобильную версию. 2.2
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров. 2.3
  - Сайт должен быть способен обрабатывать большое количество трафика. 2.4
  - Сайт должен быть доступен на различных устройствах. 2.5
implicit:
  - Поиск товара должен быть адаптирован под мультиязычность сайта 3.0
  - Пользователь должен оставить контакты на стадии авторизации или на стадии подтверждения заказа товара из корзины 3.1
  - В графе "цена" не должно быть отрицательных значений 3.2
  - Количество оставшегося товара должно быть обозначено("осталось .. шт", а не просто цифра) 3.3
  - Если товар умещается на одну страницу(лист) , то кнопки "next/следующая" не должно быть 3.4
  - Товары добавленные в корзину должны сохраняться в сессии браузера и при повторном входе на сайте корзина должна показывать те товары, что были добавлены ранее. 3.5
  - В карточке товара , при наличии нескольких фотографий товара, клиент должен иметь возможность посмотреть фотографии 3.6
  - При нажатии на "Hexlet Store" должно выводить на стартовую страницу сайта
  
  
  







