---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен быть доступен на различных устройствах.
implicit:
  - Поиск товара должен быть адаптирован под мультиязычность сайта
  - Пользователь должен оставить контакты на стадии авторизации или на стадии подтверждения заказа товара из корзины
  - В графе "цена" не должно быть отрицательных значений 
  - Количество оставшегося товара должно быть обозначено("осталось .. шт", а не просто цифра)
  - Если товар умещается на одну страницу(лист) , то кнопки "next/следующая" не должно быть
  
  
  







