---
functional:
  - Пользователь должен иметь возможность искать товары по категории. 1.0
  - Пользователь должен иметь возможность искать товары по ключевому слову. 1.1
  - Пользователь должен иметь возможность фильтровать товары по цене. 1.2
  - Пользователь должен иметь возможность фильтровать товары цвету. 1.3
  - Пользователь должен иметь возможность фильтровать товары по размеру. 1.4
  - Пользователь должен иметь возможность просматривать товары . 1.5
  - Пользователь должен иметь возможность просматривать подробную информацию о товаре. 1.6
  - Пользователь должен иметь возможность добавлять товары в корзину. 1.7
  - Пользователь должен иметь возможность просматривать содержимое корзины. 1.8
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы. 2.0
  - Сайт должен быть безопасным и защищать данные пользователя. 2.1
  - Сайт должен иметь мобильную версию. 2.2
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров. 2.3
  - Сайт должен быть способен обрабатывать большое количество трафика. 2.4
  - Сайт должен быть доступен на различных устройствах. 2.5
implicit:
  - Поиск товара должен быть адаптирован под мультиязычность сайта 3.0
  - Пользователь должен оставить контакты на стадии авторизации или на стадии подтверждения заказа товара из корзины 3.1
  - В графе "цена" не должно быть отрицательных значений 3.2
  - Фильтрация по "цене" должна быть с учетом скидки, а не начального значения 3.3
  - Количество оставшегося товара должно быть обозначено("осталось .. шт", а не просто цифра) 3.4
  - Если товар умещается на одну страницу(лист) , то кнопки "next/следующая" не должно быть 3.5
  - Товары добавленные в корзину должны сохраняться в сессии браузера и при повторном входе на сайте корзина должна показывать те товары, что были добавлены ранее. 3.6
  - В карточке товара , при наличии нескольких фотографий товара, клиент должен иметь возможность посмотреть фотографии 3.7
  - При нажатии на "Hexlet Store" должно выводить на стартовую страницу сайта 3.8
  - Возможность фильтрации по всем доступным фильтрам 3.9
  - Придобавлении товара в корзину можно указать количество 3.10
  - В корзине корректно отображается товар(который ранее выбрали) 3.11
  - Корзина корректно считает общую сумму заказа 3.12
  - Возврат в каталог из корзины .... 
  - Нажатие на заказ товара выводит окно заказа ....
  - Возможность закрыть окно заказа по кнопке "Х"...
  - - Возможность закрыть окно заказа по кнопке "Close/Заказ"....
  - Отображение товаров по тегу указанному в товаре(при нажатии)...
  
  
  
  







